### ISSUE TITLE
llava 1.5 model generate caption issue

### ISSUE THREAD

**Issue by ak2919** [yejipark-m/ConVis#1]
<img width="654" alt="image" src="https://github.com/user-attachments/assets/d5fb5a8f-8401-4856-9579-faa4035aa33e">

This problem occurs when I use the following command, how should I solve it？

`python run_scripts/caption_generation.py --model llava-1.5 --decoder convis --data_path COCO2014/val2014 --annotation_path COCO2014/annotations --output_dir ./generated_captions --images_path ./generated_images/CHAIR  `

**Comment by yejipark-m** [comment]
Thank you for your interest in our work!

It seems like you are using the original `transformers` package instead of the modified version included in our repository. Please note that our main generation function is implemented in `./transformers-4.36.2/src/transformers/generation/utils.py`.

To fix this, please follow the steps below:

1. Uninstall the original `transformers` package:
   ```bash
   pip uninstall transformers

2. Install the modified version from our repository:
   ```bash
   pip install -e ./transformers-4.36.2

If you encounter any further issues while executing the code, feel free to reach out!

**Comment by yejipark-m** [comment]
We've checked our `Dockerfile` and noticed that there's an issue: it does not automatically install our local `transformers-4.36.2`. We have updated the `README.md` to reflect this.

Please check the updated instructions, and thank you for informing us about this issue.

**Comment by ak2919** [comment]
Thanks for your reply, the issue is solved, your work is very interesting！
